### ISSUE TITLE
Stack usage clarification

### ISSUE THREAD

**Issue by deviantony** [softonic/portainer-endpoint#1]
Just gave it a try on my local environment, I was not abl to use the `stack deploy` example as the compose version (3.3) requires the latest version of the Docker engine (I have 17.05 running locally).

You might want to update the docs to specify it.

After upgrading to the latest Docker version, I had the following error when I wanted to deploy it as a stack:

```
$ docker stack deploy --compose-file docker-compose.yml portainer
service portainer: undefined network "traefik-priv"
```

Had to remove the `- traefik-priv` entry from the networks associated to the portainer service to make it work.

After that it works pretty well, you might want to precise that you just need to access the port 9000 on the host where the stack is deployed to access the Portainer instance.

After connecting to Portainer tho, the default node I was connected to was a worker and not the manager (1 manager / 2 workers cluster), it might be better to be connected to the manager directly.

**Comment by bvis** [comment]
Thanks for your test.

- I'll add the note about the docker engine version
- I've changed the version to `v3.2` as I'm not using any `v3.3` feature
- I've removed the `traefik-priv` network reference, it should't be there
- I've added the note to the doc about where to find portainer in the cluster

About the default connection to a manager I don't know how to do it in this stack. Any ideas about it?

**Comment by deviantony** [comment]
Nice update !
Well, that's actually an issue related to Portainer as it will automatically pickup the first endpoint retrieved unless available in the browser cache. Tho, not really problematic at the moment.

**Comment by bvis** [comment]
Knowing this is the expected behaviour I've added a delay to the workers before register themselves. It's more a trick than an elegant solution, but it could work.

**Comment by bvis** [comment]
I think this issue can be closed. If there's anything to clarify feel free to reopen it at any moment!
