### ISSUE TITLE
cannot host portainer with ssl

### ISSUE THREAD

**Issue by weiklr** [softonic/portainer-endpoint#10]
Hi, 
I tried running the example under "Securing Portainer using SSL"  in this link: https://portainer.readthedocs.io/en/stable/deployment.html#secure-portainer-using-ssl, and I kept getting "/certs/portainer.crt" file not found errors in the my container.

Any idea what's wrong?

**Comment by bvis** [comment]
Hi! As it's said in the README of this project this is deprecated :(

https://github.com/softonic/portainer-endpoint

I suggest you to check the official docs and the Portainer github instead: https://github.com/portainer/portainer
