### ISSUE TITLE
Add a section goal in the README

### ISSUE THREAD

**Issue by pascalandy** [softonic/portainer-endpoint#4]
As you wrote it on [portainer](https://github.com/portainer/portainer/issues/461#issue-198687920), I suggest you add this section in the readme :)

---

## The goal

Currently when running under Docker Swarm mode portainer has visibility of services and their tasks, but from the task you cannot get the logs/ssh session/etc.

In the container tab you have only access to the containers running in the host where Portainer is connected. In case you want to get this functionality on containers running on other nodes of the cluster you need to add manually the connection details, which is not a valid solution in an elastic swarm cluster where nodes are added and removed continuously.

Proposal: From the service tags, when going to the tasks list, get the same functionalities than we currently have in the containers section.

Probably in the future Docker will add more built-in functionalities to support this natively, but I have not seen this feature in their roadmap. It shouldn't be so hard to get a working solution with not so much effort.

**Comment by bvis** [comment]
@pascalandy Thanks for your suggestion.

I've updated the README, please check and feel free to reopen this task if you think something can still be improved.
