### ISSUE TITLE
Can't login if `--ssl` is enable in Portainer

### ISSUE THREAD

**Issue by letientai299** [softonic/portainer-endpoint#6]
I have portainer run [with ssl](https://portainer.readthedocs.io/en/stable/deployment.html#secure-portainer-using-ssl) via command line parameter.

```bash
docker service create -d \
  --name portainer \
  --publish 9999:9000 \
  --mount type=bind,src=//var/run/docker.sock,dst=/var/run/docker.sock \
  --mount type=volume,src=portainer_data,dst=/data \
  --mount type=bind,src=$PWD/certs,dst=/certs \
  --constraint 'node.hostname==my-machine' \
  --network portainer-network \
  portainer/portainer \
  -H unix:///var/run/docker.sock \
  --ssl \
  --sslcert /certs/my-site.crt \
  --sslkey /certs/my-site.key
```

The portainer is connected to an swarm overlay network, created with:

```bash
docker network create portainer-network -d overlay
```

And then, I deploy portainer-endpoint as a global service, with:

```bash
docker service create --with-registry-auth --detach \
  --name portainer-endpoint \
  --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
  --mount type=bind,source=/etc/hostname,target=/etc/host_hostname \
  --network portainer-network \
  --mode global \
  -e HOST_HOSTNAME=/etc/host_hostname \
  -e PORTAINER_ADDR=portainer:9000 \
  -e PORTAINER_USER=my-user \
  -e PORTAINER_PASS=my-secret \
  softonic/portainer-endpoint
```

The problem is, since portainer now serve HTTPS requests, portainer-endpoint can't connect to it.

I've tried several `PORTAINER_ADDR`, almost everything failed.

* `portainer:9000`: docker internal DNS
* `192.168.1.xxx:9999`: LAN IP
* `45.xxx.xxx.xxx:9999`: public IP

The only things work for me is the public domain name, with `https` protocol specified:

* `https://my-site.com:9999`

I've look into [the code](https://github.com/softonic/portainer-endpoint/blob/3e556601839e7ae02c0c179742bc3abb2d64fd6d/rootfs/docker-entrypoint.sh#L35), try modify curl request, but none of theme works, perhaps because Portainer run with SSL. Gave up, and hope that you can find a better solution :smile:, because I believe nodes in the LAN shouldn't have to connect via domain name.

**Comment by bvis** [comment]
Hi @letientai299 

As this container is more a temporal solution that something to maintain I'm not sure that invest time to make it work in your use case. But we could try to give it a first sight, maybe a quick solution is possible.

Could you provide the logs of the container when it's running and can't connect to portainer? Maybe the fix is as easy as to accept self-signed certificates.

**Comment by letientai299** [comment]
I'm using LetsEncrypt cert. The trick is generate LetsEncrypt for https://my-site.com using [nginx-proxy](https://github.com/jwilder/nginx-proxy) and [docker-letsencrypt-nginx-proxy-companion](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion). That cert is also valid for https://my-site.com:9000 (or any other port other than 443).

[This line](https://github.com/softonic/portainer-endpoint/blob/3e556601839e7ae02c0c179742bc3abb2d64fd6d/rootfs/docker-entrypoint.sh#L35) fails, and produce the following message:

```text
parse error: Invalid numeric literal at EOF at line 1, column 3
```

Then, portainer-endpoint container stops.

**Comment by bvis** [comment]
It seems that there's an error when connecting to the host, are you sure the certificate is valid? I f this is the case you could try to execute it with the `SSL_IGNORE_CERTIFICATION_CHECK` flag active.

Please, test it and tell me if it works as expected.

**Comment by letientai299** [comment]
The cert is valid. 

I tried your suggestion, set `SSL_IGNORE_CERTIFICATION_CHECK` to true (and to 1) for portainer-endpoint, but no luck. Also, from the code, I can't found anything related that env variable. I've thought that it's something `curl` will honor. So, I also tried connect to the portainer from within the host.

```sh
SSL_IGNORE_CERTIFICATION_CHECK=true curl localhost:9000
```

Still no luck.

**Comment by bvis** [comment]
You could try the 0.2.1 version: https://github.com/softonic/portainer-endpoint/blob/0.2.1/rootfs/docker-entrypoint.sh

**Comment by letientai299** [comment]
Thanks. `0.2.1` with `SSL_IGNORE_CERTIFICATION_CHECK` works.

BTW, I found that [latest tags is not up to date](https://github.com/softonic/portainer-endpoint/issues/9). That make me confused when compare `docker-entrypoint.sh` between this repo and within my container. :smile:
