### ISSUE TITLE
hostname doesn't exist in AWS AMI instances

### ISSUE THREAD

**Issue by gartz** [softonic/portainer-endpoint#7]
by default the `/etc/hostname` doesn't exist.

I workaround that issue executing: 
```
hostname > /etc/hostname
```
After that the stack deploy worked.

I suggest to add mention for that in the README.md file.

Thanks for the great project, really make my life easier :D

**Comment by bvis** [comment]
Hi,

Instead of use the mount solution you can avoid to mount it and use the go template format for it. I've updated the docs and the compose sample with it.

Please try it and tell me if it works as expected.

**Comment by gartz** [comment]
It worked for me, but actually, I also started using the Moby AMI images, since they're officially supported by docker. They work perfectly with your implementation, thanks.

**Comment by bvis** [comment]
From your comment I guess I can close this task. Feel free to reopen it if needed.
